/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hryt_iov_speech_emptyproaddndk_JNITools */

#ifndef _Included_com_hryt_iov_speech_emptyproaddndk_JNITools
#define _Included_com_hryt_iov_speech_emptyproaddndk_JNITools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hryt_iov_speech_emptyproaddndk_JNITools
 * Method:    addNum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hryt_iov_speech_emptyproaddndk_JNITools_addNum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
